export const words = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'I',
  'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
  'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
  'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
  'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
  'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take',
  'person', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other',
  'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also',
  'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way',
  'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us',
  'is', 'are', 'was', 'were', 'has', 'had', 'does', 'did', 'said', 'went',
  'people', 'man', 'woman', 'child', 'world', 'school', 'state', 'family', 'student',
  'group', 'country', 'problem', 'hand', 'part', 'place', 'case', 'week', 'company',
  'system', 'program', 'question', 'government', 'number', 'night', 'point', 'home',
  'water', 'room', 'mother', 'area', 'money', 'story', 'fact', 'month', 'lot',
  'right', 'study', 'book', 'eye', 'job', 'word', 'business', 'issue', 'side',
  'kind', 'head', 'house', 'service', 'friend', 'father', 'power', 'hour', 'game',
  'line', 'end', 'member', 'law', 'car', 'city', 'community', 'name', 'president',
  'team', 'minute', 'idea', 'kid', 'body', 'information', 'parent', 'face', 'others',
  'level', 'office', 'door', 'health', 'art', 'war', 'history', 'party', 'result',
  'change', 'morning', 'reason', 'research', 'girl', 'guy', 'moment', 'air', 'teacher',
  'force', 'education', 'very', 'every', 'long', 'life', 'little', 'old', 'big',
  'high', 'different', 'small', 'large', 'next', 'early', 'young', 'important', 'few',
  'public', 'bad', 'same', 'able', 'to', 'be', 'come', 'go', 'see', 'look',
  'find', 'tell', 'ask', 'work', 'seem', 'feel', 'try', 'leave', 'call', 'need',
  'want', 'become', 'put', 'mean', 'keep', 'let', 'begin', 'help', 'talk', 'turn',
  'start', 'show', 'hear', 'play', 'run', 'move', 'live', 'believe', 'hold', 'bring',
  'happen', 'write', 'provide', 'sit', 'stand', 'lose', 'pay', 'meet', 'include',
  'continue', 'set', 'learn', 'change', 'lead', 'understand', 'watch', 'follow',
  'stop', 'create', 'speak', 'read', 'allow', 'add', 'spend', 'grow', 'open',
  'walk', 'win', 'offer', 'remember', 'love', 'consider', 'appear', 'buy', 'wait',
  'serve', 'die', 'send', 'expect', 'build', 'stay', 'fall', 'cut', 'reach',
  'kill', 'remain', 'suggest', 'raise', 'pass', 'sell', 'require', 'report',
  'decide', 'pull', 'code', 'keyboard', 'developer', 'software', 'project',
  'interface', 'design', 'style', 'component', 'function', 'variable', 'array'
];
